introduce debian:bookworm
ern/arm64/efi/init.c: Assembler messages:
kern/arm64/efi/init.c:34: Error: no such instruction: `mrs %rax,cntvct_el0'
kern/arm64/efi/init.c:47: Error: no such instruction: `mrs %rax,cntfrq_el0'
make[3]: *** [Makefile:42653: kern/arm64/efi/kernel_exec-init.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f kern/.deps-core/kernel_exec-acpi.Tpo kern/.deps-core/kernel_exec-acpi.Po